'use client'

import { useState, useRef, useCallback } from 'react'
import { Document, Page, pdfjs } from 'react-pdf'
import Mark from 'mark.js'
import 'react-pdf/dist/Page/AnnotationLayer.css'
import 'react-pdf/dist/Page/TextLayer.css'

// Required setup for pdf.js worker in Next.js
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`

interface PdfViewerProps {
  fileUrl: string
  issues?: any
}

export function PdfViewer({ fileUrl, issues }: PdfViewerProps) {
  const [numPages, setNumPages] = useState<number>()
  const viewerRef = useRef<HTMLDivElement>(null)

  function onDocumentLoadSuccess({ numPages }: { numPages: number }) {
    setNumPages(numPages)
  }

  // The Magic "Resume Worded" Highlighter
  const applyHighlights = useCallback(() => {
    if (!viewerRef.current || !issues) return;

    // Grab all text layers generated by react-pdf
    const textLayers = viewerRef.current.querySelectorAll('.react-pdf__Page__textContent');
    
    textLayers.forEach(layer => {
      const marker = new Mark(layer as HTMLElement);
      
      // Clear previous marks if re-rendering
      marker.unmark(); 

      // HIGHLIGHT HIGH PRIORITY (Weak Verbs, Pronouns)
      if (issues.high) {
        issues.high.forEach((issue: any) => {
          if (issue.word) {
            marker.mark(issue.word, {
              className: 'bg-rose-200/80 text-rose-900 border-b-2 border-rose-500 font-bold cursor-help transition-colors hover:bg-rose-300',
              accuracy: 'partially',
              acrossElements: true // CRITICAL: PDF text is often split across multiple <span> tags!
            });
          }
        });
      }

      // HIGHLIGHT MEDIUM PRIORITY (Buzzwords, Repetitions)
      if (issues.medium) {
        issues.medium.forEach((issue: any) => {
          if (issue.word) {
            marker.mark(issue.word, {
              className: 'bg-indigo-200/80 text-indigo-900 border-b-2 border-indigo-500 font-bold cursor-help transition-colors hover:bg-indigo-300',
              accuracy: 'partially',
              acrossElements: true
            });
          }
        });
      }

      // HIGHLIGHT LOW PRIORITY (Filler Words, Typos)
      if (issues.low) {
        issues.low.forEach((issue: any) => {
          if (issue.word) {
            marker.mark(issue.word, {
              className: 'bg-amber-200/80 text-amber-900 border-b-2 border-amber-500 font-bold cursor-help transition-colors hover:bg-amber-300',
              accuracy: 'partially',
              acrossElements: true
            });
          }
        });
      }
    });
  }, [issues]);

  return (
    <div className="w-full flex flex-col items-center" ref={viewerRef}>
      <Document
        file={fileUrl}
        onLoadSuccess={onDocumentLoadSuccess}
        className="flex flex-col gap-8 items-center"
        loading={
          <div className="flex flex-col items-center justify-center p-12 text-slate-500">
            <svg className="animate-spin h-8 w-8 text-indigo-600 mb-4" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
            <p className="font-semibold">Rendering Advanced PDF Engine...</p>
            <p className="text-xs mt-2 text-slate-400">Loading fonts and styles</p>
          </div>
        }
      >
        {Array.from(new Array(numPages || 0), (el, index) => (
          <div key={`page_${index + 1}`} className="shadow-2xl border border-slate-200 bg-white relative">
            <Page 
              pageNumber={index + 1} 
              width={800} 
              renderTextLayer={true}
              renderAnnotationLayer={false}
              onRenderSuccess={applyHighlights} // Run Mark.js the second the text layer hits the DOM!
            />
          </div>
        ))}
      </Document>
    </div>
  )
}
